### ISSUE TITLE
Downstream issue with Llama 2 added tokens

### ISSUE THREAD

**Issue by tmostak** [h2oai/h2o-llmstudio#297]
This is more a question/ask for help than any issue report, but after fine-tuning many models (both in the LLama family and not) with this platform, yesterday I attempted fine-tunes on both the 7B and 13B Llama V2 models that were just released.

Everything went fine/as expected until I tried to run GGML-converted weights for the model in `llama.cpp`. I then received the following error:

```
error loading model: llama.cpp: tensor 'tok_embeddings.weight' has wrong shape; expected  5120 x 32000, got  5120 x 32001
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/Users/todd/data/model_weights/llama_v2/llama_v2_13b_sql_v1/ggml-model-q4_0.bin'
```

I indeed see the extra pad_token in the `added_tokens.json` file in the HuggingFace HF variant of the model that were downloaded before pre-training (see the repo https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main), but strangely enough when I attempted to GGML-convert the raw weights from the repo (without fine-tuning), they generated a model with vocabulary size 32000, which then ran in llama.cpp without issue.

Does anyone know how I might fix/workaround this issue? Not sure if this is a quirk with llama.cpp, or if there is a way using LLM Studio to not actually add this extra pad token to the vocabulary in the generated model. Thanks in advance for your help!

**Comment by psinger** [comment]
This is currently a known issue that tokenizer length and model size do not match:
https://github.com/huggingface/transformers/issues/24899

So what happens when you fine-tune in LLM Studio, is that we need to extend the model size by one, to accommodate the tokenizer length.

If GGML does not allow extended sizes, this might be an issue. But maybe there is a way in GGML to configure the size?

As a quick workaround you could comment out this block and re-train your model:
https://github.com/h2oai/h2o-llmstudio/blob/main/llm_studio/src/utils/modeling_utils.py#L571

This would very likely make the training work, but would break if the last token would be tokenized. 

The better solution is to wait for HF to fix it.

**Comment by psinger** [comment]
This is now fixed in the original model weights. If you retrain all should be good.

**Comment by tmostak** [comment]
Thanks @psinger for your help with this!
