### ISSUE TITLE
[BUG] Multi GPU training fails

### ISSUE THREAD

**Issue by shaileshp367** [h2oai/h2o-llmstudio#318]
### To Reproduce

Hello

When I use multiple GPU(8 GPU in rig) and create new experiment then generate below error, Please check below image

Please help

![image](https://github.com/h2oai/h2o-llmstudio/assets/123468018/1cdab990-94d6-40e7-9450-b5e93e6c5c82)

**Comment by maxjeblick** [comment]
Hi @shaileshp367, this issue sounds hard to debug. DDP training works on our setup and the error could potentially originate from an issue unrelated to LLM Studio (insufficient hardware resources seem to be a common source).

To better understand the origin of the error could you try to pinpoint where LLM Studio fails by
- share your configuration used, if possible
- share the complete error log, if possible.
- running with **default** settings on less than 8 GPUs and increase #gpus until training fails? Also, permute gpus used to test if a particular GPU may cause issues.
- re-running a failed configuration with very resource sensitive settings (e.g. using `facebook/opt-125m` with batch size 2 and sequence lengths prompt32/answer32/total64, using the default settings, otherwise)?

**Comment by shaileshp367** [comment]
@maxjeblick 

Thanks for your reply

I have used Ubuntu 22.04.2 LTS and my hardware  is bellow please check

![image](https://github.com/h2oai/h2o-llmstudio/assets/123468018/6cf4cafa-5998-4bf9-ad86-c3bbcb50cc90)

**Comment by maxjeblick** [comment]
Thanks for sharing. Could you in addition, share the configuration yaml used for the failed experiment? Also, could you try rerunning the experiment with different settings as indicated above? To exclude any data specific issues, please try with the default OASST dataset.

As mentioned, the error could originate from hardware issues, see e.g. [here](https://discuss.huggingface.co/t/torch-distributed-elastic-multiprocessing-errors-childfailederror/28242/5) and thus would be out of scope to fix here.

**Comment by psinger** [comment]
@shaileshp367 any updates on this?

**Comment by psinger** [comment]
Closing, please re-open if issues still persist.
