### ISSUE TITLE
LLM Studio crash every time I try to start training

### ISSUE THREAD

**Issue by Ender436** [h2oai/h2o-llmstudio#435]
### 🐛 Bug

I am using settings that are only slightly different than previous successful runs, I'm not quite understanding what is wrong. Any help would be appreciated! Here is the error I'm getting:

stacktrace
Traceback (most recent call last):

File “/home/user/h2o-llmstudio/./llm_studio/app_utils/handlers.py”, line 172, in handle should_list_current_experiments = await experiment_run(

File “/home/user/h2o-llmstudio/./llm_studio/app_utils/sections/experiment.py”, line 536, in experiment_run start_experiment(cfg=cfg, q=q, pre=pre)

File “/home/user/h2o-llmstudio/./llm_studio/app_utils/utils.py”, line 1728, in start_experiment p = start_process(

File “/home/user/h2o-llmstudio/./llm_studio/app_utils/utils.py”, line 145, in start_process p = subprocess.Popen(

File “/usr/lib/python3.10/subprocess.py”, line 971, in init self._execute_child(args, executable, preexec_fn, close_fds,

File “/usr/lib/python3.10/subprocess.py”, line 1783, in _execute_child env_list.append(k + b’=’ + os.fsencode(v))

File “/usr/lib/python3.10/os.py”, line 811, in fsencode filename = fspath(filename) # Does type-checking of filename.

TypeError: expected str, bytes or os.PathLike object, not NoneType

Error
None

### To Reproduce

yaml file is not written, otherwise I would include it

### LLM Studio version

Git Version
9d6e9470447ebbc96e54346365fcb168868a9033

**Comment by Ender436** [comment]
I also seem to be getting errors where it is saying that the directory already exists, but not only did it not exist before I tried running that experiment, it isn't even the name that I had put into the field for naming the experiment. Sorry if I'm missing something obvious.

**Comment by maxjeblick** [comment]
Thanks for posting the issue, I'll investigate it. Did you update llm studio from a previous version or is it a fresh install?

**Comment by Ender436** [comment]
Thanks, I’ll have to try that, it is a fresh install, I installed just yesterday. I also noticed it might be something to do with settings changed in the GUI not being saved or something, because I’ve noticed a few times when creating an experiment and typing in the hugging face model, I’d hit enter or click out of it, and the field would clear as soon as I did so. Thanks again for the help.

**Comment by Ender436** [comment]
I followed the steps you provided, and the error still happened.

**Comment by maxjeblick** [comment]
Thanks a lot for testing. In the meanwhile, I was able to reproduce the error, following the following steps:
1. Start LLM Studio
2. Settings -> Restore Default Settings
3. Set "Do not Save credentials permanently"
4. Save Settings
5. Load Settings
6. Restart the app
7. Start a new experiment

In this case, `env_vars` read as  `{'NEPTUNE_API_TOKEN': None, 'OPENAI_API_KEY': None, 'GPT_EVAL_MAX': '100'}`
and experiment fails with the error message above. This should be fixed with #440.

---------------------------
You also mentioned a couple of other peculiarities:


> I also seem to be getting errors where it is saying that the directory already exists

This sounds weird. Please feel free to open a new issue if this error still exists and is reproducible. 


> I’ve noticed a few times when creating an experiment and typing in the hugging face model, I’d hit enter or click out of it, and the field would clear as soon as I did so.

This is expected behavior. The current implementation that uses h2o-wave as a frontend does not save the current user settings the user types in (there is usually no communication between the frontend and the backend when the user changes a setting, so changes get lost). Technically, it would be possible to parse and save the user settings. However, parsing will trigger the re-rendering of the frontend which may cause some lags, especially if LLm Studio is used on a remote machine. I hope this makes sense.

**Comment by maxjeblick** [comment]
@Ender436 
The issue should now be fixed.
