### ISSUE TITLE
[CODE IMPROVEMENT] Follow up on classification problem type

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#479]
### 🔧 Proposed code refactoring

Some features we can add for text classification:

- Remove generation parameters from Prediction Config, as not needed
- Disable Chat Window 
- Remove answer int from tokenized insights
- Extract a separate dataset class for classification

### Motivation

- Better UX 
- More disentangled codebase

**Comment by a-ghorbani** [comment]
I'm not sure about the implementation complexity, but I'd like to propose the following improvements (if they are not by design so):
- Automatically infer the number of classes from the target column, rather than requiring the user to set it manually.
- Ensure only appropriate loss functions are selectable. For instance, for multi-class classification, the selected one by default is BinaryCrossEntropyLoss, which obviously won't work.

**Comment by maxjeblick** [comment]
Closing this issue, implemented by #481 and #499.

@a-ghorbani Currently, we don't plan to automatically infer/encode number of classes.
