### ISSUE TITLE
[CODE IMPROVEMENT] Push to Huggingface improvements

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#5]
Currently, we only push the model weights to Huggingface. We could improve this process by adding some of these additional artifacts:

- [x] Tokenizer
- [ ] LLM Studio CFG / YAML
- [ ] Automated Model card
- [ ] Preprocessing/Postprocessing Pipeline

**Comment by JulianGerhard21** [comment]
Hi,

@psinger - I haven't had the time to read every part of the documentation, so here's a quick question: Can I push the result of a finetuning towards the huggingface hub so that I can use it without the studio afterwards (e.g. as Gradio Space), or is there a format-related adjustment?

Kind regards
Julian
