### ISSUE TITLE
[BUG] Failed during model fine-tuning

### ISSUE THREAD

**Issue by yum-yeom** [h2oai/h2o-llmstudio#527]
#### Failed while training the model. 
- Model: EleutherAI/polyglot-en-5.8b
- Train Data: About 9,000 cases

#### Additional explanation
- Initially, the training seems to be working fine, but after about 2%, the training ETA suddenly increases dramatically.
- When I set up a total of 3 GPUs and run the model training, the first GPU seems to be unusable. 
- The attached file contains the Docker and UI error statements.
[docker_error_log_231205.txt](https://github.com/h2oai/h2o-llmstudio/files/13554283/docker_error_log_231205.txt)
[gui_error_log_231205.txt](https://github.com/h2oai/h2o-llmstudio/files/13554284/gui_error_log_231205.txt)

- GPU information in use.
![image](https://github.com/h2oai/h2o-llmstudio/assets/51901261/f5cc4944-a367-4d28-abf8-eeaf1bab37cd)

If I need anything else, I'll ask for it.

### To Reproduce

Performing model training with EleutherAI/polyglot-en-5.8b.

- I was using the original version (v0.0.5) well, but suddenly the program became too slow and the above happened after reinstalling the latest version (v1.2.0).
- Same issue after reinstalling back to the original version (v0.0.5)

### LLM Studio version

- version: v0.0.5-dev

**Comment by psinger** [comment]
Hi @yum-yeom -

unfortunately this is very hard to debug as it might be related to an issue on your docker / ddp setup, here are a few things you can try:

- Please up-date to the latest version of LLM Studio, 0.0.5 is quite outdated - but I dont think this will solve your issue
- Try running it on a single GPU instead of selecting multiple ones. If this works, we can narrow it down to DDP not working
- Try to set the following env variable: `export NCCL_P2P_DISABLE=1`
- And please monitor the GPU usage while the experiment is stuck / running

**Comment by yum-yeom** [comment]
Hello. First of all, thank you for your quick response.

I'll test the 4 things you mentioned, and if that doesn't work, I'll try to utilize the CLI method (which I've found works well).

Thanks again for your help!

**Comment by psinger** [comment]
Did you have a chance to test it @yum-yeom ?
